# Generated by Django 4.2.2 on 2024-08-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wholesaler", "0003_alter_wholesaler_options_wholesaler_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Продавец")),
                ("description", models.TextField(verbose_name="Описание")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("city", models.CharField(max_length=50, verbose_name="Город")),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                ("house", models.CharField(max_length=10, verbose_name="Дом")),
                (
                    "debt",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Задолженность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "wholesaler",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wholesaler",
                        to="wholesaler.wholesaler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продавец",
                "verbose_name_plural": "Продавцы",
                "ordering": ("city",),
            },
        ),
    ]
