# Generated by Django 4.2.2 on 2024-08-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wholesaler", "0006_remove_wholesaler_created_at_and_more"),
        ("sellers", "0002_remove_seller_debt_seller_creditors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="seller",
            name="wholesaler",
            field=models.ManyToManyField(
                blank=True,
                related_name="wholesaler",
                to="wholesaler.wholesaler",
                verbose_name="Поставщик",
            ),
        ),
    ]
