# Generated by Django 4.2.2 on 2024-08-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manufacturers", "0004_remove_product_manufacturer_manufacturer_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wholesaler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Наименование оптовика"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("city", models.CharField(max_length=50, verbose_name="Город")),
                ("street", models.CharField(max_length=100, verbose_name="Улица")),
                ("house", models.CharField(max_length=10, verbose_name="Дом")),
                ("debt", models.FloatField(verbose_name="Задолженность")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manufacturers.manufacturer",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оптовик",
                "verbose_name_plural": "Оптовики",
            },
        ),
    ]
