# Generated by Django 4.2.2 on 2024-08-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wholesaler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wholesaler",
            name="supplier",
        ),
    ]
