# Generated by Django 4.2.2 on 2024-08-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0009_alter_manufacturer_options_and_more"),
        ("wholesaler", "0002_remove_wholesaler_supplier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wholesaler",
            options={
                "ordering": ("city",),
                "verbose_name": "Оптовик",
                "verbose_name_plural": "Оптовики",
            },
        ),
        migrations.AddField(
            model_name="wholesaler",
            name="supplier",
            field=models.ManyToManyField(
                blank=True, related_name="wholesalers", to="manufacturers.manufacturer"
            ),
        ),
    ]
