# Generated by Django 4.2.2 on 2024-08-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0009_alter_manufacturer_options_and_more"),
        ("wholesaler", "0003_alter_wholesaler_options_wholesaler_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wholesaler",
            name="supplier",
        ),
        migrations.AddField(
            model_name="wholesaler",
            name="manufacturer",
            field=models.ManyToManyField(
                blank=True, related_name="manufacturer", to="manufacturers.manufacturer"
            ),
        ),
    ]
