# Generated by Django 4.2.2 on 2024-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditors", "0001_initial"),
        ("wholesaler", "0004_remove_wholesaler_supplier_wholesaler_manufacturer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wholesaler",
            name="debt",
        ),
        migrations.AddField(
            model_name="wholesaler",
            name="creditors",
            field=models.ManyToManyField(
                blank=True,
                related_name="creditors_for_wholesaler",
                to="creditors.creditor",
                verbose_name="Кредиторы",
            ),
        ),
    ]
