# Generated by Django 4.2.2 on 2024-08-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0010_remove_manufacturer_created_at"),
        ("wholesaler", "0005_remove_wholesaler_debt_wholesaler_creditors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wholesaler",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="wholesaler",
            name="manufacturer",
            field=models.ManyToManyField(
                blank=True,
                related_name="manufacturer",
                to="manufacturers.manufacturer",
                verbose_name="Поставщик",
            ),
        ),
    ]
