# Generated by Django 4.2.2 on 2024-08-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="debt",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Задолженность"
            ),
        ),
    ]
