# Generated by Django 4.2.2 on 2024-08-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0003_alter_manufacturer_debt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="manufacturer",
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manufacturers.product",
                verbose_name="Производитель",
            ),
        ),
    ]
