# Generated by Django 4.2.2 on 2024-08-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0005_remove_manufacturer_product_product_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manufacturers.manufacturer",
                verbose_name="Производитель",
            ),
        ),
    ]
