# Generated by Django 4.2.2 on 2024-08-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wholesaler", "0002_remove_wholesaler_supplier"),
        ("manufacturers", "0006_alter_product_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="wholesalers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="wholesalers",
                to="wholesaler.wholesaler",
            ),
        ),
    ]
