# Generated by Django 4.2.2 on 2024-08-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0008_alter_manufacturer_wholesalers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ("city",),
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.RemoveField(
            model_name="manufacturer",
            name="wholesalers",
        ),
    ]
