# Generated by Django 4.2.2 on 2024-08-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0009_alter_manufacturer_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturer",
            name="created_at",
        ),
    ]
