# Generated by Django 4.2.2 on 2024-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creditor", models.CharField(max_length=100, verbose_name="Кредитор")),
                (
                    "amount",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Сумма долга"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кредитор",
                "verbose_name_plural": "Кредиторы",
            },
        ),
    ]
